name: sqflite_git
description: "Template for local data storage using sqflite package"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

# launcher icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/ic_launcher.png'
  adaptive_icon_foreground: 'assets/icons/ic_launcher.png'
  adaptive_icon_background: '#ffffff'